C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitdirectcontrol(setupfunc)
      external setupfunc
      integer jones
      common /directcontrol/ jones
      call setupfunc(jones)
      end


