name: Local tests (not owner repository)

on:
  push:
    branches: [xsa-dev-patch-2]
  pull_request:
    branches: [xsa-dev-patch-2]
  release:
    types: [created]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine regex
          pip install tensorflow
          pip install -e ".[tests]" --progress-bar off

      - name: Test with pytest
        run: |
          pytest --cov=autokeras --cov-report xml:coverage.xml

  format:
    name: Check the code format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine regex
          pip install tensorflow
          pip install -e .
          pip install -r docs/requirements.txt

      - name: Run pre-commit
        run: bash shell/pre-commit.sh

  build-docs:
    name: Build the docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine regex
          pip install tensorflow
          pip install -e .
          pip install -r docs/requirements.txt

      - name: Build the docs
        run: |
          cd docs
          python autogen.py
          mkdocs build

  deploy:
    needs: [build, format, build-docs]
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine regex
          pip install tensorflow

